site_name: Evecyclopedia

theme:
  name: material
  icon:
    logo: material/orbit
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: ru
  palette: 
    scheme: slate
    primary: indigo
    accent: deep orange

nav:
  - Home index.md

plugins:
  - search:
      lang:
        - en
        - ru

extra:
  generator: false
  consent:
    title: Cookie consent
    description: >-
      Мы используем файлы cookie для распознавания ваших повторных посещений и предпочтений, а также
      а также для измерения эффективности нашей документации и того, находят ли пользователи
      пользователи то, что ищут. С вашего согласия вы помогаете нам
      сделать нашу документацию лучше.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
      github:
        name: GitHub
        checked: true
    actions:
      - accept
      - manage

copyright: >
  Copyright &copy; 2023 Evecylopedia –
  <a href="#__consent">Изменить настройки cookie </a>